<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>aisp</string>
    <key>scopeName</key>
    <string>source.aisp</string>
    <key>fileTypes</key>
    <array>
      <string>as</string>
      <string>atkd</string>
      <string>aipd</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b0x[0-9a-fA-F]+|\b\d+)</string>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:true|false)\b</string>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:if|elif|endif|else)\b|^#include .+$</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:unk|id|str)\b</string>
            <key>name</key>
            <string>support.type</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(label)\s*([\w\d_]+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.unquoted</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bvar(?:2[0-4]|1?[0-9])\b</string>
            <key>name</key>
            <string>variable.other</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.ts</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(")|((?:[^\\\n])$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.ts</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.newline.ts</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.ts</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((?://).*$)</string>
            <key>name</key>
            <string>comment</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\*\/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>